-- مركز الحملات الذكي: تعريف موحد للحملة والجمهور والقناة والنتيجة.
-- الإرسال الفعلي يبقى عبر بوابات واتساب/IVR الحالية؛ هذا المخطط يوحد
-- التخطيط والمراجعة والتتبع ومهام الموظفين فقط.

create table if not exists public.smart_campaigns (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  objective text not null check (objective in ('collection', 'reactivation', 'sales', 'service')),
  status text not null default 'draft'
    check (status in ('draft', 'review', 'ready', 'scheduled', 'running', 'completed', 'needs_decision', 'cancelled')),
  audience_definition jsonb not null default '{}'::jsonb,
  source_keys text[] not null default array[]::text[],
  channel text check (channel is null or channel in ('whatsapp', 'ivr', 'employee_task', 'export')),
  channel_config jsonb not null default '{}'::jsonb,
  protection_snapshot jsonb not null default '{}'::jsonb,
  audience_count integer not null default 0 check (audience_count >= 0),
  ready_count integer not null default 0 check (ready_count >= 0),
  excluded_count integer not null default 0 check (excluded_count >= 0),
  financial_amount numeric(18,2) not null default 0,
  result_summary jsonb not null default '{}'::jsonb,
  scheduled_at timestamptz,
  launched_at timestamptz,
  completed_at timestamptz,
  created_by uuid not null default auth.uid() references auth.users(id),
  updated_by uuid default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint smart_campaigns_name_not_blank check (btrim(name) <> '')
);

create unique index if not exists smart_campaigns_name_unique
  on public.smart_campaigns (lower(name));
create index if not exists smart_campaigns_status_updated_idx
  on public.smart_campaigns (status, updated_at desc);
create index if not exists smart_campaigns_objective_updated_idx
  on public.smart_campaigns (objective, updated_at desc);
create index if not exists smart_campaigns_created_by_idx
  on public.smart_campaigns (created_by, updated_at desc);
create index if not exists smart_campaigns_updated_by_idx
  on public.smart_campaigns (updated_by);

create table if not exists public.smart_campaign_events (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.smart_campaigns(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  constraint smart_campaign_events_type_not_blank check (btrim(event_type) <> '')
);

create index if not exists smart_campaign_events_campaign_idx
  on public.smart_campaign_events (campaign_id, created_at desc);
create index if not exists smart_campaign_events_created_by_idx
  on public.smart_campaign_events (created_by);

create table if not exists public.smart_campaign_tasks (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.smart_campaigns(id) on delete cascade,
  recipient_key text not null,
  phone text,
  display_name text,
  amount numeric(18,2) not null default 0,
  assigned_to uuid not null default auth.uid() references auth.users(id),
  status text not null default 'todo'
    check (status in ('todo', 'contacted', 'done', 'snoozed', 'cancelled')),
  context jsonb not null default '{}'::jsonb,
  completed_at timestamptz,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint smart_campaign_tasks_recipient_not_blank check (btrim(recipient_key) <> ''),
  unique (campaign_id, recipient_key)
);

create index if not exists smart_campaign_tasks_assignee_idx
  on public.smart_campaign_tasks (assigned_to, status, updated_at desc);
create index if not exists smart_campaign_tasks_campaign_idx
  on public.smart_campaign_tasks (campaign_id, status);
create index if not exists smart_campaign_tasks_created_by_idx
  on public.smart_campaign_tasks (created_by);

create or replace function public.touch_smart_campaign_record()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists smart_campaigns_touch_updated_at on public.smart_campaigns;
create trigger smart_campaigns_touch_updated_at
before update on public.smart_campaigns
for each row execute function public.touch_smart_campaign_record();

drop trigger if exists smart_campaign_tasks_touch_updated_at on public.smart_campaign_tasks;
create trigger smart_campaign_tasks_touch_updated_at
before update on public.smart_campaign_tasks
for each row execute function public.touch_smart_campaign_record();

alter table public.smart_campaigns enable row level security;
alter table public.smart_campaign_events enable row level security;
alter table public.smart_campaign_tasks enable row level security;

drop policy if exists smart_campaigns_select on public.smart_campaigns;
create policy smart_campaigns_select on public.smart_campaigns
for select to authenticated
using (public.app_has_any_permission(array[
  'whatsapp.view_log', 'campaigns.send', 'campaigns.ivr', 'receivables.view', 'sales.view'
]));

drop policy if exists smart_campaigns_insert on public.smart_campaigns;
create policy smart_campaigns_insert on public.smart_campaigns
for insert to authenticated
with check (
  created_by = (select auth.uid())
  and public.app_has_any_permission(array['campaigns.send', 'campaigns.ivr'])
);

drop policy if exists smart_campaigns_update on public.smart_campaigns;
create policy smart_campaigns_update on public.smart_campaigns
for update to authenticated
using (public.app_has_any_permission(array['campaigns.send', 'campaigns.ivr']))
with check (
  updated_by = (select auth.uid())
  and public.app_has_any_permission(array['campaigns.send', 'campaigns.ivr'])
);

drop policy if exists smart_campaign_events_select on public.smart_campaign_events;
create policy smart_campaign_events_select on public.smart_campaign_events
for select to authenticated
using (public.app_has_any_permission(array[
  'whatsapp.view_log', 'campaigns.send', 'campaigns.ivr', 'receivables.view', 'sales.view'
]));

drop policy if exists smart_campaign_events_insert on public.smart_campaign_events;
create policy smart_campaign_events_insert on public.smart_campaign_events
for insert to authenticated
with check (
  created_by = (select auth.uid())
  and public.app_has_any_permission(array['campaigns.send', 'campaigns.ivr'])
);

drop policy if exists smart_campaign_tasks_select on public.smart_campaign_tasks;
create policy smart_campaign_tasks_select on public.smart_campaign_tasks
for select to authenticated
using (
  assigned_to = (select auth.uid())
  or public.app_has_any_permission(array['campaigns.send', 'campaigns.ivr', 'collections.view_all'])
);

drop policy if exists smart_campaign_tasks_insert on public.smart_campaign_tasks;
create policy smart_campaign_tasks_insert on public.smart_campaign_tasks
for insert to authenticated
with check (
  created_by = (select auth.uid())
  and public.app_has_any_permission(array['campaigns.send', 'campaigns.ivr'])
);

drop policy if exists smart_campaign_tasks_update on public.smart_campaign_tasks;
create policy smart_campaign_tasks_update on public.smart_campaign_tasks
for update to authenticated
using (
  assigned_to = (select auth.uid())
  or public.app_has_any_permission(array['campaigns.send', 'campaigns.ivr', 'collections.view_all'])
)
with check (
  assigned_to = (select auth.uid())
  or public.app_has_any_permission(array['campaigns.send', 'campaigns.ivr', 'collections.view_all'])
);

revoke all on table public.smart_campaigns from anon;
revoke all on table public.smart_campaign_events from anon;
revoke all on table public.smart_campaign_tasks from anon;

grant select, insert, update on table public.smart_campaigns to authenticated;
grant select, insert on table public.smart_campaign_events to authenticated;
grant select, insert, update on table public.smart_campaign_tasks to authenticated;
grant usage, select on sequence public.smart_campaign_events_id_seq to authenticated;

revoke all on function public.touch_smart_campaign_record() from public, anon, authenticated;
