-- Customer growth operating loop.
-- Reuses the existing merchant lifecycle, sales follow-up and CRM activity
-- ledgers instead of creating a parallel customer state. No message is sent.

create table if not exists public.customer_growth_outcomes (
  id bigint generated by default as identity primary key,
  phone text not null,
  reason_code text not null,
  outcome text not null,
  sales_stage text not null,
  activity_type text not null,
  next_action_at timestamptz,
  note text,
  owner_id uuid references public.profiles(id) on delete set null,
  recorded_by uuid references public.profiles(id) on delete set null,
  recorded_at timestamptz not null default now(),
  constraint customer_growth_outcomes_stage_check check (
    sales_stage in ('contacted', 'qualified', 'nurture', 'won', 'lost')
  ),
  constraint customer_growth_outcomes_activity_check check (
    activity_type in ('note', 'call', 'whatsapp', 'meeting', 'email')
  )
);

alter table public.customer_growth_outcomes enable row level security;
revoke all on table public.customer_growth_outcomes from public, anon, authenticated;
grant select, insert on table public.customer_growth_outcomes to service_role;
grant usage, select on sequence public.customer_growth_outcomes_id_seq to service_role;
create index if not exists customer_growth_outcomes_phone_reason_at_idx
  on public.customer_growth_outcomes(phone, reason_code, recorded_at desc);
create index if not exists customer_growth_outcomes_owner_next_idx
  on public.customer_growth_outcomes(owner_id, next_action_at)
  where sales_stage not in ('won', 'lost');

create or replace function public.customer_growth_action_queue(
  p_limit integer default 400,
  p_owner text default null,
  p_journey text default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
begin
  if (select auth.uid()) is null
     or not public.app_has_any_permission(array[
       'collections.view', 'sales.view', 'overview.view', 'crm.view'
     ]) then
    raise exception 'not_allowed';
  end if;

  return (
    with actions as (
      select *
      from public.customer_engagement_next_actions(
        greatest(1, least(coalesce(p_limit, 400), 1000)), p_owner, p_journey
      )
    ), latest_outcome as (
      select distinct on (public.norm_sa_phone(outcome.phone), outcome.reason_code)
        public.norm_sa_phone(outcome.phone) as phone,
        outcome.reason_code,
        outcome.sales_stage,
        outcome.next_action_at,
        outcome.recorded_at
      from public.customer_growth_outcomes outcome
      order by public.norm_sa_phone(outcome.phone), outcome.reason_code, outcome.recorded_at desc
    )
    select coalesce(jsonb_agg(to_jsonb(action) order by action.priority desc, action.amount desc nulls last), '[]'::jsonb)
    from actions action
    left join latest_outcome outcome
      on outcome.phone = public.norm_sa_phone(action.phone)
     and outcome.reason_code = action.reason_code
    where outcome.phone is null
       or (
         outcome.sales_stage not in ('won', 'lost')
         and (outcome.next_action_at is null or outcome.next_action_at <= now())
       )
       or outcome.recorded_at < now() - interval '90 days'
  );
end;
$function$;

create or replace function public.customer_growth_operating_snapshot(
  p_days integer default 30
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_days integer := greatest(7, least(coalesce(p_days, 30), 180));
begin
  if (select auth.uid()) is null
     or not public.app_has_any_permission(array[
       'collections.view', 'sales.view', 'overview.view', 'crm.view', 'receivables.view'
     ]) then
    raise exception 'not_allowed';
  end if;

  return (
    with latest_snapshot as (
      select m.snapshot_id, max(m.uploaded_at) as uploaded_at
      from public.merchants m
      group by m.snapshot_id
      order by max(m.uploaded_at) desc
      limit 1
    ), base as (
      select
        m.*,
        public.norm_sa_phone(m.phone) as normalized_phone,
        case
          when coalesce(m.shipment_count, 0) = 0
               and (
                 m.integration_type is not null
                 or coalesce(m.wallet_balance, 0) > 0.5
                 or m.profile_status = 'مكتمل'
                 or m.verification_status = 'موثق'
               ) then 'ready_first_shipment'
          when coalesce(m.shipment_count, 0) = 0 then 'registered'
          when m.last_shipment_at >= now() - interval '30 days' then 'active'
          when m.last_shipment_at >= now() - interval '60 days' then 'at_risk'
          else 'stopped'
        end as lifecycle_stage
      from public.merchants m
      where m.snapshot_id = (select snapshot_id from latest_snapshot)
    ), scoped_phones as (
      select distinct normalized_phone as phone
      from base
      where normalized_phone is not null
    ), linked_stores as (
      select distinct b.store_id
      from base b
      join public.customer_merchant_links link on link.store_id = b.store_id
      join public.customer_ar ar on ar.contact_name = link.customer_name
    ), open_work as (
      select f.*
      from public.retargeting_followups f
      join scoped_phones p on p.phone = public.norm_sa_phone(f.phone)
      where coalesce(f.sales_stage, 'new') not in ('won', 'lost', 'disqualified')
    ), growth_work as (
      select distinct on (public.norm_sa_phone(outcome.phone), outcome.reason_code)
        outcome.*
      from public.customer_growth_outcomes outcome
      join scoped_phones p on p.phone = public.norm_sa_phone(outcome.phone)
      order by public.norm_sa_phone(outcome.phone), outcome.reason_code, outcome.recorded_at desc
    ), period_events as (
      select e.*
      from public.merchant_lifecycle_events e
      where e.observed_at >= now() - make_interval(days => v_days)
    ), touches as (
      select
        public.norm_sa_phone(a.entity_ref) as phone,
        max(a.occurred_at) as last_touch_at
      from public.crm_activities a
      where a.entity_type = 'platform_merchant'
        and a.occurred_at >= now() - make_interval(days => v_days)
        and public.norm_sa_phone(a.entity_ref) is not null
      group by public.norm_sa_phone(a.entity_ref)
    ), payment_rows as (
      select distinct t.phone, payment.zoho_id, payment.amount
      from touches t
      join base b on b.normalized_phone = t.phone
      join public.customer_merchant_links link on link.store_id = b.store_id
      join public.zoho_payments payment on payment.customer_name = link.customer_name
      where payment.date >= t.last_touch_at::date
        and payment.date <= current_date
    ), shipment_after_touch as (
      select distinct t.phone
      from touches t
      join period_events event
        on public.norm_sa_phone(event.phone) = t.phone
       and event.event_type in ('first_shipment', 'shipping_resumed', 'reactivated')
       and event.observed_at >= t.last_touch_at
    ), new_cohort as (
      select *
      from base
      where created_at_platform >= now() - make_interval(days => v_days)
    )
    select jsonb_build_object(
      'period_days', v_days,
      'source_snapshot', jsonb_build_object(
        'id', (select snapshot_id from latest_snapshot),
        'uploaded_at', (select uploaded_at from latest_snapshot)
      ),
      'identity', jsonb_build_object(
        'stores', (select count(*) from base),
        'valid_phone', (select count(*) from base where normalized_phone is not null),
        'linked_to_zoho', (select count(*) from linked_stores),
        'unlinked_to_zoho', (
          select count(*) from base b
          where not exists (select 1 from linked_stores linked where linked.store_id = b.store_id)
        ),
        'multi_store_accounts', (
          select count(*) from (
            select normalized_phone
            from base
            where normalized_phone is not null
            group by normalized_phone
            having count(*) > 1
          ) grouped
        ),
        'coverage_pct', (
          select case when count(*) = 0 then 0
            else round(100.0 * count(*) filter (
              where normalized_phone is not null
                and exists (select 1 from linked_stores linked where linked.store_id = base.store_id)
            ) / count(*), 1)
          end
          from base
        )
      ),
      'lifecycle', jsonb_build_object(
        'registered', (select count(*) from base where lifecycle_stage = 'registered'),
        'ready_first_shipment', (select count(*) from base where lifecycle_stage = 'ready_first_shipment'),
        'active', (select count(*) from base where lifecycle_stage = 'active'),
        'at_risk', (select count(*) from base where lifecycle_stage = 'at_risk'),
        'stopped', (select count(*) from base where lifecycle_stage = 'stopped'),
        'reactivated_period', (
          select count(distinct coalesce(public.norm_sa_phone(phone), 'store:' || store_id))
          from period_events where event_type in ('reactivated', 'shipping_resumed')
        )
      ),
      'execution', jsonb_build_object(
        'open', (select count(*) from open_work),
        'assigned', (select count(*) from open_work where owner_id is not null),
        'unassigned', (select count(*) from open_work where owner_id is null),
        'overdue', (select count(*) from open_work where next_action_at < now()),
        'missing_next_action', (select count(*) from open_work where next_action_at is null),
        'touched_period', (select count(*) from touches),
        'won_period', (
          select count(*) from public.retargeting_followups f
          join scoped_phones p on p.phone = public.norm_sa_phone(f.phone)
          where f.won_at >= now() - make_interval(days => v_days)
        ),
        'lost_period', (
          select count(*) from public.retargeting_followups f
          join scoped_phones p on p.phone = public.norm_sa_phone(f.phone)
          where f.lost_at >= now() - make_interval(days => v_days)
        ),
        'outcomes_recorded', (
          select count(*) from public.customer_growth_outcomes outcome
          join scoped_phones p on p.phone = public.norm_sa_phone(outcome.phone)
          where outcome.recorded_at >= now() - make_interval(days => v_days)
        ),
        'scheduled_growth_followups', (
          select count(*) from growth_work
          where sales_stage not in ('won', 'lost') and next_action_at > now()
        )
      ),
      'outcomes', jsonb_build_object(
        'new_accounts', (select count(*) from new_cohort),
        'new_accounts_shipped', (select count(*) from new_cohort where coalesce(shipment_count, 0) > 0),
        'activation_rate_pct', (
          select case when count(*) = 0 then 0
            else round(100.0 * count(*) filter (where coalesce(shipment_count, 0) > 0) / count(*), 1)
          end
          from new_cohort
        ),
        'first_shipments', (
          select count(distinct coalesce(public.norm_sa_phone(phone), 'store:' || store_id))
          from period_events where event_type = 'first_shipment'
        ),
        'shipping_after_touch', (select count(*) from shipment_after_touch),
        'customers_paid_after_touch', (select count(distinct phone) from payment_rows),
        'paid_after_touch', (select coalesce(round(sum(amount)::numeric, 2), 0) from payment_rows)
      ),
      'sending', jsonb_build_object(
        'enabled', false,
        'mode', 'review_only'
      )
    )
  );
end;
$function$;

create or replace function public.customer_growth_profile(p_phone text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_phone text := public.norm_sa_phone(p_phone);
begin
  if (select auth.uid()) is null
     or not public.app_has_any_permission(array[
       'collections.view', 'sales.view', 'overview.view', 'crm.view', 'receivables.view'
     ]) then
    raise exception 'not_allowed';
  end if;
  if v_phone is null then raise exception 'invalid_phone'; end if;

  return (
    with latest_snapshot as (
      select m.snapshot_id
      from public.merchants m
      group by m.snapshot_id
      order by max(m.uploaded_at) desc
      limit 1
    ), stores as (
      select m.*
      from public.merchants m
      where m.snapshot_id = (select snapshot_id from latest_snapshot)
        and public.norm_sa_phone(m.phone) = v_phone
    ), linked_customers as (
      select distinct link.customer_name
      from stores s
      join public.customer_merchant_links link on link.store_id = s.store_id
    ), finance as (
      select
        coalesce(sum(ar.total_due), 0)::numeric as total_due,
        coalesce(sum(ar.collectible_due), 0)::numeric as collectible_due,
        coalesce(sum(ar.opening_due), 0)::numeric as opening_due,
        coalesce(sum(ar.open_invoices), 0)::bigint as open_invoices
      from public.customer_ar ar
      join linked_customers linked on linked.customer_name = ar.contact_name
    ), followup as (
      select f.*, profile.name as owner_name
      from public.retargeting_followups f
      left join public.profiles profile on profile.id = f.owner_id
      where public.norm_sa_phone(f.phone) = v_phone
      order by f.updated_at desc
      limit 1
    ), last_touch as (
      select max(a.occurred_at) as occurred_at
      from public.crm_activities a
      where a.entity_type = 'platform_merchant'
        and public.norm_sa_phone(a.entity_ref) = v_phone
    ), payment_rows as (
      select distinct payment.zoho_id, payment.amount
      from linked_customers linked
      join public.zoho_payments payment on payment.customer_name = linked.customer_name
      where (select occurred_at from last_touch) is not null
        and payment.date >= (select occurred_at::date from last_touch)
    ), lifecycle as (
      select event.*
      from public.merchant_lifecycle_events event
      where public.norm_sa_phone(event.phone) = v_phone
         or event.store_id in (select store_id from stores)
      order by event.observed_at desc
      limit 20
    ), activities as (
      select activity.*, profile.name as owner_name
      from public.crm_activities activity
      left join public.profiles profile on profile.id = activity.owner_id
      where activity.entity_type = 'platform_merchant'
        and public.norm_sa_phone(activity.entity_ref) = v_phone
      order by activity.occurred_at desc
      limit 20
    ), outcomes as (
      select outcome.*, profile.name as owner_name
      from public.customer_growth_outcomes outcome
      left join public.profiles profile on profile.id = outcome.owner_id
      where public.norm_sa_phone(outcome.phone) = v_phone
      order by outcome.recorded_at desc
      limit 20
    )
    select jsonb_build_object(
      'customer_key', 'phone:' || v_phone,
      'phone', v_phone,
      'name', coalesce((select store_name from stores order by shipment_count desc nulls last limit 1), v_phone),
      'stage', case
        when exists (select 1 from stores where coalesce(shipment_count, 0) > 0 and last_shipment_at >= now() - interval '30 days') then 'active'
        when exists (select 1 from stores where coalesce(shipment_count, 0) > 0 and last_shipment_at >= now() - interval '60 days') then 'at_risk'
        when exists (select 1 from stores where coalesce(shipment_count, 0) > 0) then 'stopped'
        when exists (select 1 from stores where integration_type is not null or coalesce(wallet_balance, 0) > 0.5 or profile_status = 'مكتمل' or verification_status = 'موثق') then 'ready_first_shipment'
        else 'registered'
      end,
      'identity', jsonb_build_object(
        'stores', coalesce((select jsonb_agg(jsonb_build_object(
          'store_id', store_id, 'store_name', store_name, 'status', status,
          'shipments', shipment_count, 'last_shipment_at', last_shipment_at,
          'wallet', wallet_balance, 'billing_type', billing_type,
          'integration_type', integration_type
        ) order by shipment_count desc nulls last) from stores), '[]'::jsonb),
        'zoho_customers', coalesce((select jsonb_agg(jsonb_build_object(
          'name', ar.contact_name, 'zoho_id', ar.zoho_id, 'balance_status', ar.balance_integrity_status
        ) order by ar.contact_name) from public.customer_ar ar
          join linked_customers linked on linked.customer_name = ar.contact_name), '[]'::jsonb)
      ),
      'finance', (select jsonb_build_object(
        'total_due', round(total_due, 2), 'collectible_due', round(collectible_due, 2),
        'opening_due', round(opening_due, 2), 'open_invoices', open_invoices
      ) from finance),
      'followup', coalesce((select jsonb_build_object(
        'status', status, 'sales_stage', sales_stage, 'owner_id', owner_id,
        'owner_name', owner_name, 'next_action_at', next_action_at,
        'next_action_type', next_action_type, 'last_touch_at', last_touch_at,
        'contact_attempts', contact_attempts, 'notes', notes
      ) from followup), '{}'::jsonb),
      'impact_after_last_touch', jsonb_build_object(
        'last_touch_at', (select occurred_at from last_touch),
        'paid_amount', (select coalesce(round(sum(amount)::numeric, 2), 0) from payment_rows),
        'shipment_events', (select count(*) from lifecycle where event_type in ('first_shipment', 'shipping_resumed', 'reactivated') and observed_at >= (select occurred_at from last_touch))
      ),
      'lifecycle', coalesce((select jsonb_agg(to_jsonb(event)) from lifecycle event), '[]'::jsonb),
      'activities', coalesce((select jsonb_agg(to_jsonb(activity)) from activities activity), '[]'::jsonb),
      'outcomes', coalesce((select jsonb_agg(to_jsonb(outcome)) from outcomes outcome), '[]'::jsonb)
    )
  );
end;
$function$;

create or replace function public.record_customer_growth_outcome(
  p_phone text,
  p_reason_code text,
  p_outcome text,
  p_next timestamptz default null,
  p_activity_type text default 'call',
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_uid uuid := (select auth.uid());
  v_phone text := public.norm_sa_phone(p_phone);
  v_stage text;
  v_existing public.retargeting_followups%rowtype;
  v_financial_hold boolean := false;
  v_owner uuid;
begin
  if v_uid is null then raise exception 'not_allowed'; end if;
  if p_reason_code in ('wallet_neg', 'debt') then
    if not public.app_has_any_permission(array['collections.update_stage']) then
      raise exception 'not_allowed';
    end if;
  elsif not public.app_has_any_permission(array['sales.manage']) then
    raise exception 'not_allowed';
  end if;

  if v_phone is null then raise exception 'invalid_phone'; end if;
  if p_outcome not in (
    'contacted', 'interested', 'no_answer', 'needs_followup',
    'returned', 'converted', 'not_interested', 'price_issue'
  ) then raise exception 'invalid_outcome'; end if;
  if p_activity_type not in ('note', 'call', 'whatsapp', 'meeting', 'email') then
    raise exception 'invalid_activity_type';
  end if;

  v_stage := case
    when p_outcome in ('returned', 'converted') then 'won'
    when p_outcome = 'not_interested' then 'lost'
    when p_outcome = 'interested' then 'qualified'
    when p_outcome in ('no_answer', 'needs_followup') then 'nurture'
    else 'contacted'
  end;

  if v_stage not in ('won', 'lost') and p_next is null then
    raise exception 'next_action_required';
  end if;
  if v_stage = 'lost' and nullif(btrim(coalesce(p_note, '')), '') is null then
    raise exception 'loss_reason_required';
  end if;

  select * into v_existing
  from public.retargeting_followups
  where public.norm_sa_phone(phone) = v_phone
  order by updated_at desc
  limit 1
  for update;

  if found and v_existing.owner_id is not null and v_existing.owner_id <> v_uid
     and not public.crm_can_see_all() and not public.crm_has_permission('crm.assign') then
    raise exception 'not_allowed';
  end if;

  select exists (
    select 1 from public.v_platform_commercial_routing routing
    where routing.phone = v_phone and routing.financial_hold
  ) into v_financial_hold;
  v_owner := coalesce(v_existing.owner_id, v_uid);

  insert into public.customer_growth_outcomes (
    phone, reason_code, outcome, sales_stage, activity_type,
    next_action_at, note, owner_id, recorded_by
  ) values (
    v_phone, p_reason_code, p_outcome, v_stage, p_activity_type,
    case when v_stage in ('won', 'lost') then null else p_next end,
    nullif(btrim(p_note), ''), v_owner, v_uid
  );

  if not v_financial_hold then
    insert into public.retargeting_followups (
    phone, status, sales_stage, owner_id, next_action_at, next_action_type,
    notes, last_touch_at, first_contact_at, contact_attempts,
    loss_reason, lost_at, won_at, updated_by, updated_at
  ) values (
    v_phone, p_outcome, v_stage, v_owner,
    case when v_stage in ('won', 'lost') then null else p_next end,
    case when p_activity_type in ('call', 'whatsapp', 'meeting', 'email') then p_activity_type else 'other' end,
    nullif(btrim(p_note), ''), now(), now(), 1,
    case when v_stage = 'lost' then nullif(btrim(p_note), '') end,
    case when v_stage = 'lost' then now() end,
    case when v_stage = 'won' then now() end,
    v_uid, now()
  )
  on conflict (phone) do update set
    status = excluded.status,
    sales_stage = excluded.sales_stage,
    owner_id = coalesce(public.retargeting_followups.owner_id, excluded.owner_id),
    next_action_at = excluded.next_action_at,
    next_action_type = excluded.next_action_type,
    notes = coalesce(excluded.notes, public.retargeting_followups.notes),
    last_touch_at = now(),
    first_contact_at = coalesce(public.retargeting_followups.first_contact_at, now()),
    contact_attempts = public.retargeting_followups.contact_attempts + 1,
    loss_reason = case when excluded.sales_stage = 'lost' then excluded.loss_reason else null end,
    lost_at = case when excluded.sales_stage = 'lost' then coalesce(public.retargeting_followups.lost_at, now()) else null end,
    won_at = case when excluded.sales_stage = 'won' then coalesce(public.retargeting_followups.won_at, now()) else null end,
    updated_by = v_uid,
    updated_at = now();

    if p_outcome is distinct from coalesce(v_existing.status, 'new') then
      insert into public.retargeting_status_log(phone, old_status, new_status, changed_by)
      values (v_phone, v_existing.status, p_outcome, v_uid);
    end if;
  end if;

  insert into public.crm_activities (
    entity_type, entity_ref, kind, disposition, summary, body,
    channel_ref, occurred_at, owner_id, created_by
  ) values (
    'platform_merchant', v_phone,
    case when p_reason_code in ('wallet_neg', 'debt') then 'collections_' else 'sales_' end || p_activity_type,
    p_outcome,
    'نتيجة من مهام العملاء: ' || coalesce(p_reason_code, 'general'),
    nullif(btrim(p_note), ''), p_reason_code, now(),
    v_owner, v_uid
  );

  return jsonb_build_object(
    'phone', v_phone, 'outcome', p_outcome, 'sales_stage', v_stage,
    'next_action_at', case when v_stage in ('won', 'lost') then null else p_next end,
    'recorded_at', now(), 'financial_hold_preserved', v_financial_hold,
    'sending_triggered', false
  );
end;
$function$;

revoke all on function public.customer_growth_action_queue(integer, text, text) from public, anon;
revoke all on function public.customer_growth_operating_snapshot(integer) from public, anon;
revoke all on function public.customer_growth_profile(text) from public, anon;
revoke all on function public.record_customer_growth_outcome(text, text, text, timestamptz, text, text) from public, anon;
grant execute on function public.customer_growth_action_queue(integer, text, text) to authenticated, service_role;
grant execute on function public.customer_growth_operating_snapshot(integer) to authenticated, service_role;
grant execute on function public.customer_growth_profile(text) to authenticated, service_role;
grant execute on function public.record_customer_growth_outcome(text, text, text, timestamptz, text, text) to authenticated, service_role;

comment on function public.customer_growth_action_queue(integer, text, text) is
  'Review queue with completed or future-scheduled growth outcomes suppressed. It never sends a message.';
comment on function public.customer_growth_operating_snapshot(integer) is
  'Read-only growth operating snapshot. Uses objective Lamha lifecycle events and labels post-touch outcomes without claiming causality.';
comment on function public.customer_growth_profile(text) is
  'Unified growth profile joining Lamha stores, Zoho customer links, finance, ownership, activities and objective lifecycle events.';
comment on function public.record_customer_growth_outcome(text, text, text, timestamptz, text, text) is
  'Records a reviewed customer outcome, owner, SLA and CRM activity. It never sends a WhatsApp message or starts a campaign.';
